-- MySQL Script generated by MySQL Workbench
-- Mon Dec 20 15:18:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema KitchenOfWisdom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KitchenOfWisdom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KitchenOfWisdom` DEFAULT CHARACTER SET utf8 ;
USE `KitchenOfWisdom` ;

-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tTypeIngredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tTypeIngredient` (
  `TYPI_Id` INT NOT NULL AUTO_INCREMENT,
  `TYPI_Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TYPI_Id`),
  UNIQUE INDEX `UK1_TYPI_Id` (`TYPI_Id` ASC),
  UNIQUE INDEX `UK2_TYPI_Nom` (`TYPI_Nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tIngredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tIngredient` (
  `ING_Id` INT NOT NULL AUTO_INCREMENT,
  `ING_Nom` VARCHAR(50) NOT NULL,
  `ING_Description` VARCHAR(150) NULL,
  `TYPI_Id` INT NOT NULL,
  PRIMARY KEY (`ING_Id`),
  UNIQUE INDEX `UK1_ING_Id` (`ING_Id` ASC),
  INDEX `IX_FK_tIngredient_TYPI_Id` (`TYPI_Id` ASC),
  UNIQUE INDEX `UK2_ING_Nom` (`ING_Nom` ASC),
  CONSTRAINT `FK_tIngredient_TYPI_Id`
    FOREIGN KEY (`TYPI_Id`)
    REFERENCES `KitchenOfWisdom`.`tTypeIngredient` (`TYPI_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tSource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tSource` (
  `SOU_Id` INT NOT NULL AUTO_INCREMENT,
  `SOU_ImageRecette` VARCHAR(45) NULL,
  PRIMARY KEY (`SOU_Id`),
  UNIQUE INDEX `UK1_SOU_Id` (`SOU_Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tTypeRecette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tTypeRecette` (
  `TYPR_Id` INT NOT NULL AUTO_INCREMENT,
  `TYPR_Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TYPR_Id`),
  UNIQUE INDEX `IdtTypeRecette_UNIQUE` (`TYPR_Id` ASC),
  UNIQUE INDEX `TYPR_Nom_UNIQUE` (`TYPR_Nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tRecette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tRecette` (
  `REC_Id` INT NOT NULL AUTO_INCREMENT,
  `REC_Nom` VARCHAR(150) NOT NULL,
  `REC_Description` VARCHAR(2500) NULL,
  `REC_TempsPreparation` VARCHAR(45) NULL,
  `REC_TempsCuisson` VARCHAR(45) NULL,
  `REC_NombrePersonne` VARCHAR(45) NULL,
  `SOU_Id` INT NULL,
  `TYPR_Id` INT NOT NULL,
  PRIMARY KEY (`REC_Id`),
  INDEX `IX_FK_tRecette_SOU_Id` (`SOU_Id` ASC),
  UNIQUE INDEX `UK1_REC_Id` (`REC_Id` ASC),
  INDEX `IX_FK_tRecette_TYPR_Id` (`TYPR_Id` ASC),
  CONSTRAINT `FK_tRecette_SOU_Id`
    FOREIGN KEY (`SOU_Id`)
    REFERENCES `KitchenOfWisdom`.`tSource` (`SOU_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_tTypeRecette_TYPR_Id`
    FOREIGN KEY (`TYPR_Id`)
    REFERENCES `KitchenOfWisdom`.`tTypeRecette` (`TYPR_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tLivre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tLivre` (
  `SOU_Id` INT NOT NULL,
  `LIV_Nom` VARCHAR(100) NOT NULL,
  `LIV_Edition` VARCHAR(50) NULL,
  `LIV_ImageLivre` VARCHAR(45) NULL,
  PRIMARY KEY (`SOU_Id`),
  CONSTRAINT `FK_tLivre_SOU_Id`
    FOREIGN KEY (`SOU_Id`)
    REFERENCES `KitchenOfWisdom`.`tSource` (`SOU_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tAutre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tAutre` (
  `SOU_Id` INT NOT NULL,
  `AUT_Nom` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`SOU_Id`),
  CONSTRAINT `FK_tAutre_SOU_Id`
    FOREIGN KEY (`SOU_Id`)
    REFERENCES `KitchenOfWisdom`.`tSource` (`SOU_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tSiteWeb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tSiteWeb` (
  `SOU_Id` INT NOT NULL,
  `SIT_Nom` INT NOT NULL,
  `SIT_LienURL` VARCHAR(500) NULL,
  PRIMARY KEY (`SOU_Id`),
  CONSTRAINT `FK_tSiteWeb_SOU_Id`
    FOREIGN KEY (`SOU_Id`)
    REFERENCES `KitchenOfWisdom`.`tSource` (`SOU_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tUnite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tUnite` (
  `UNI_Id` INT NOT NULL,
  `UNI_Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UNI_Id`),
  UNIQUE INDEX `UK1_UNI_Nom` (`UNI_Nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tComposant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tComposant` (
  `REC_Id` INT NOT NULL,
  `ING_Id` INT NOT NULL,
  `UNI_Id` INT NOT NULL,
  `COM_Quantity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`REC_Id`, `ING_Id`, `UNI_Id`),
  INDEX `IX_FK_tComposant_ING_Id` (`ING_Id` ASC),
  INDEX `IX_FK_tComposant_REC_Id` (`REC_Id` ASC),
  INDEX `IX_FK_tComposant_UNI_Id` (`UNI_Id` ASC),
  CONSTRAINT `FK_tComposant_REC_Id`
    FOREIGN KEY (`REC_Id`)
    REFERENCES `KitchenOfWisdom`.`tRecette` (`REC_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_tComposant_ING_Id`
    FOREIGN KEY (`ING_Id`)
    REFERENCES `KitchenOfWisdom`.`tIngredient` (`ING_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_tComposant_UNI_Id`
    FOREIGN KEY (`UNI_Id`)
    REFERENCES `KitchenOfWisdom`.`tUnite` (`UNI_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
