-- MySQL Script generated by MySQL Workbench
-- Tue Dec 14 14:39:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema KitchenOfWisdom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KitchenOfWisdom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KitchenOfWisdom` DEFAULT CHARACTER SET utf8 ;
USE `KitchenOfWisdom` ;

-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tTypeIngredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tTypeIngredient` (
  `IdTypeIngredient` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdTypeIngredient`),
  UNIQUE INDEX `IdTypeIngredient_UNIQUE` (`IdTypeIngredient` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tIngredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tIngredient` (
  `IdIngredient` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(50) NOT NULL,
  `Description` VARCHAR(150) NULL,
  `tTypeIngredient_IdTypeIngredient` INT NOT NULL,
  PRIMARY KEY (`IdIngredient`, `tTypeIngredient_IdTypeIngredient`),
  INDEX `fk_tIngredient_tTypeIngredient1_idx` (`tTypeIngredient_IdTypeIngredient` ASC),
  UNIQUE INDEX `IdIngredient_UNIQUE` (`IdIngredient` ASC),
  CONSTRAINT `fk_tIngredient_tTypeIngredient1`
    FOREIGN KEY (`tTypeIngredient_IdTypeIngredient`)
    REFERENCES `KitchenOfWisdom`.`tTypeIngredient` (`IdTypeIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tTypeRecette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tTypeRecette` (
  `IdtTypeRecette` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdtTypeRecette`),
  UNIQUE INDEX `IdtTypeRecette_UNIQUE` (`IdtTypeRecette` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tSource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tSource` (
  `IdtSource` INT NOT NULL AUTO_INCREMENT,
  `ImageRecette` VARCHAR(45) NULL,
  PRIMARY KEY (`IdtSource`),
  UNIQUE INDEX `IdtSource_UNIQUE` (`IdtSource` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tRecette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tRecette` (
  `idRecette` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(150) NOT NULL,
  `Description` VARCHAR(500) NULL,
  `TempsPreparation` VARCHAR(45) NULL,
  `TempsCuisson` VARCHAR(45) NULL,
  `NombrePersonne` VARCHAR(45) NULL,
  `tTypeRecette_IdtTypeRecette` INT NOT NULL,
  `tSource_IdtSource` INT NULL,
  PRIMARY KEY (`idRecette`),
  INDEX `fk_tRecette_tTypeRecette1_idx` (`tTypeRecette_IdtTypeRecette` ASC) ,
  INDEX `fk_tRecette_tSource1_idx` (`tSource_IdtSource` ASC) ,
  UNIQUE INDEX `idRecette_UNIQUE` (`idRecette` ASC) ,
  CONSTRAINT `fk_tRecette_tTypeRecette1`
    FOREIGN KEY (`tTypeRecette_IdtTypeRecette`)
    REFERENCES `KitchenOfWisdom`.`tTypeRecette` (`IdtTypeRecette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tRecette_tSource1`
    FOREIGN KEY (`tSource_IdtSource`)
    REFERENCES `KitchenOfWisdom`.`tSource` (`IdtSource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tRecette_has_tIngredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tRecette_has_tIngredient` (
  `tRecette_idRecette` INT NOT NULL,
  `tIngredient_IdIngredient` INT NOT NULL,
  PRIMARY KEY (`tRecette_idRecette`, `tIngredient_IdIngredient`),
  INDEX `fk_tRecette_has_tIngredient_tIngredient1_idx` (`tIngredient_IdIngredient` ASC),
  INDEX `fk_tRecette_has_tIngredient_tRecette_idx` (`tRecette_idRecette` ASC),
  CONSTRAINT `fk_tRecette_has_tIngredient_tRecette`
    FOREIGN KEY (`tRecette_idRecette`)
    REFERENCES `KitchenOfWisdom`.`tRecette` (`idRecette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tRecette_has_tIngredient_tIngredient1`
    FOREIGN KEY (`tIngredient_IdIngredient`)
    REFERENCES `KitchenOfWisdom`.`tIngredient` (`IdIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tLivre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tLivre` (
  `tSource_IdtSource` INT NOT NULL,
  `Nom` VARCHAR(100) NOT NULL,
  `Edition` VARCHAR(50) NULL,
  `ImageLivre` VARCHAR(45) NULL,
  INDEX `fk_tLivre_tSource1_idx` (`tSource_IdtSource` ASC),
  PRIMARY KEY (`tSource_IdtSource`),
  CONSTRAINT `fk_tLivre_tSource1`
    FOREIGN KEY (`tSource_IdtSource`)
    REFERENCES `KitchenOfWisdom`.`tSource` (`IdtSource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tAutre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tAutre` (
  `tSource_IdtSource` INT NOT NULL,
  `Nom` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`tSource_IdtSource`),
  INDEX `fk_tAutre_tSource1_idx` (`tSource_IdtSource` ASC),
  CONSTRAINT `fk_tAutre_tSource1`
    FOREIGN KEY (`tSource_IdtSource`)
    REFERENCES `KitchenOfWisdom`.`tSource` (`IdtSource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KitchenOfWisdom`.`tSiteWeb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KitchenOfWisdom`.`tSiteWeb` (
  `tSource_IdtSource` INT NOT NULL,
  `Nom` INT NOT NULL,
  `LienURL` VARCHAR(500) NULL,
  PRIMARY KEY (`tSource_IdtSource`),
  INDEX `fk_tSiteWeb_tSource1_idx` (`tSource_IdtSource` ASC),
  CONSTRAINT `fk_tSiteWeb_tSource1`
    FOREIGN KEY (`tSource_IdtSource`)
    REFERENCES `KitchenOfWisdom`.`tSource` (`IdtSource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
